/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A20 */

#ifndef _Included_A20
#define _Included_A20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A20
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_A20_display
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
