/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDemo */

#ifndef _Included_NativeDemo
#define _Included_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDemo
 * Method:    showMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeDemo_showMessage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
